runtime: python39

entrypoint: python3 main.py

# If you use non-default names for the secrets you define in the Secrets Manager
#  (https://console.cloud.google.com/security/secret-manager), change them here
env_variables:
#  ALLOWED_HOST_SECRET_NAME: "gate_opener_allowed_host"
#  AUTH_TOKEN_SECRET_NAME: "gate_opener_auth_token"
#  SOCKETIO_PATH_SECRET_NAME: "gate_opener_socketio_path"

# This section makes sure we always upgrade to HTTPS
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

# This makes sure we don't exceed the free tier
automatic_scaling:
  max_instances: 1
