# (Required) The hostname of your MQTT broker
MQTT_SERVER_HOSTNAME: some.host.name

# (Optional) The port of your MQTT broker. Defaults to 8883.
# MQTT_SERVER_PORT: "12345"

# (Optional) The username to use to log in to the MQTT broker. If not given, the MQTT client won't use a username/password.
# MQTT_SERVER_USERNAME: some_username

# (Optional) The password to use to log in to the MQTT broker. If not given, the MQTT client won't use a username/password.
# MQTT_SERVER_PASSWORD: some_password

# (Optional) Whether or not to use an encrypted TLS connection to connect to the MQTT broker, including verifying that it has a valid certificate. Defaults to true. Set to false to disable encryption.
# MQTT_USE_TLS: true

# (Optional) The topic to use to trigger the gate opener. Defaults to gate-opener/open.
# MQTT_COMMAND_TOPIC: some/topic

# (Optional) The topic to listen on to receive confirmation messages from the gate opener. Defaults to gate-opener/opened.
# MQTT_RESPONSE_TOPIC: some_other/topic

# (Required) A json list of access tokens to use to access the service on the web. These tokens are the only thing protecting your gate opener from being accessed by anyone, so they should be long and random so that they can't be guessed or brute-forced
ACCESS_TOKENS_LIST: >
  [
    "entry1",
    "entry2"
  ]
